---
aws_region: us-east-1
aws_profile: dev
network_state: present
vpc_name: "jenkins-{{ aws_region}}-vpc"
vpc_cidr: 10.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}c"
  # private-3:
  #   cidr: 10.0.3.0/24
  #   az: "{{ aws_region }}d"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
